### ISSUE TITLE
Export Flow types

### ISSUE THREAD

**Issue by taion** [4Catalyzer/graphql-node-resource#8]
Can't cut over Flow-using packages right now.

**Comment by jquense** [comment]
What is the right way to do this? Mirror the files as .flow.js?

**Comment by taion** [comment]
Looks like https://github.com/graphql/graphql-js/blob/54f631ff3238affdddb4dc736fc282b620d70b15/package.json#L38

**Comment by taion** [comment]
Fixed in #9
